services:
  jellyfin-tvxml:
    build: .
    image: ghcr.io/ha1fdan/jellyfin-tvxml:latest
    container_name: jellyfin-tvxml
    restart: unless-stopped
    ports:
      - "8765:8765"
    volumes:
      - ./streams.json:/app/streams.json:ro
